import {
  MD3LightTheme as DefaultLightTheme,
  MD3DarkTheme as DefaultDarkTheme,
  configureFonts,
  MD3Theme,
} from 'react-native-paper';

const fontConfig = {
  fontFamily: 'Inter-Regular',
  headlineLarge: { fontFamily: 'Inter_28pt-Regular', fontSize: 32 },
  headlineMedium: { fontFamily: 'Inter_28pt-Regular', fontSize: 28 },
  headlineSmall: { fontFamily: 'Inter_28pt-Regular', fontSize: 24 },
  titleLarge: { fontFamily: 'Inter_28pt-Regular', fontSize: 22 },
  titleMedium: { fontFamily: 'Inter_28pt-Bold', fontSize: 16 },
  titleSmall: { fontFamily: 'Inter_28pt-SemiBold', fontSize: 14 },
  bodyLarge: { fontFamily: 'Inter_24pt-Regular', fontSize: 16 },
  bodyMedium: { fontFamily: 'Inter_24pt-Bold', fontSize: 14 },
  labelLarge: { fontFamily: 'Inter_18pt-Regular', fontSize: 14 },
  labelMedium: { fontFamily: 'Inter_18pt-Bold', fontSize: 12 },
  labelSmall: { fontFamily: 'Inter_18pt-Thin', fontSize: 11 },
};

export const lightTheme: MD3Theme = {
  ...DefaultLightTheme,
  roundness: 12,
  colors: {
    ...DefaultLightTheme.colors,
    primary: '#4F46E5',
    onPrimary: '#FFFFFF',
    primaryContainer: '#E0E7FF',
    onPrimaryContainer: '#1E1B4B',
    secondary: '#5856D6',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#E0E0FF',
    onSecondaryContainer: '#191953',
    tertiary: '#059669',
    onTertiary: '#FFFFFF',
    background: '#F8FAFC',
    onBackground: '#1E293B',
    surface: '#FFFFFF',
    onSurface: '#1E293B',
    surfaceVariant: '#F1F5F9',
    onSurfaceVariant: '#475569',
    outline: '#CBD5E1',
    error: '#DC2626',
    onError: '#FFFFFF',
    errorContainer: '#FECACA',
    onErrorContainer: '#991B1B',
  },
  fonts: configureFonts({ config: fontConfig }),
};

export const darkTheme: MD3Theme = {
  ...DefaultDarkTheme,
  roundness: 12,
  colors: {
    ...DefaultDarkTheme.colors,
    primary: '#A5B4FC',
    onPrimary: '#1E1B4B',
    primaryContainer: '#3730A3',
    onPrimaryContainer: '#E0E7FF',
    secondary: '#A8A6FF',
    onSecondary: '#2A285E',
    secondaryContainer: '#413F76',
    onSecondaryContainer: '#E0E0FF',
    tertiary: '#6EE7B7',
    onTertiary: '#043A2A',
    background: '#0F172A',
    onBackground: '#E2E8F0',
    surface: '#1E293B',
    onSurface: '#E2E8F0',
    surfaceVariant: '#334155',
    onSurfaceVariant: '#94A3B8',
    outline: '#475569',
    error: '#F87171',
    onError: '#601414',
    errorContainer: '#B91C1C',
    onErrorContainer: '#FECACA',
  },
  fonts: configureFonts({ config: fontConfig }),
};
